
export enum EmailType {
    CAMPAIGN_CREATED = 'CAMPAIGN_CREATED',
    DONATION_RECEIVED = 'DONATION_RECEIVED',
    CAMPAIGN_ENDED = 'CAMPAIGN_ENDED',
    CAMPAIGN_GOAL_REACHED = 'CAMPAIGN_GOAL_REACHED'
  }